/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'harishb' at '1/15/16 10:54 PM' with Gradle 2.5
 *
 * @author harishb, @date 1/15/16 10:54 PM
 */
public class Library {
    public static void main(String args[]) {
        System.out.println("This is hi");
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
